FROM golang:latest

# Install Delve
RUN go install github.com/go-delve/delve/cmd/dlv@latest

# Install fresh
RUN go install github.com/gravityblast/fresh@latest


# Set the working directory to the root of the app
WORKDIR /app

# Copy the go.mod and go.sum files to the working directory
COPY src/go.mod src/go.sum ./

# Download the dependencies
RUN go mod download


# Copy the rest of the source code to the working directory
COPY src/ .

# Build the app
# RUN go build -o backend .

# Expose the port that the app will listen on
EXPOSE 8080

# Run fresh to monitor the source code and automatically rebuild and reload the app when changes are detected
# CMD ["fresh"]

